# Generated by Django 2.0.13 on 2019-02-19 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery', models.CharField(max_length=200)),
                ('beer_name', models.CharField(max_length=200)),
                ('beer_type', models.CharField(max_length=200)),
                ('abv', models.FloatField()),
                ('purchased_location', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six')], default=3)),
                ('tasting_notes', models.TextField()),
                ('tasted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('taster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
