# Generated by Django 2.0.13 on 2019-02-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateBeer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taste',
            name='img_file',
            field=models.FileField(null=True, upload_to='rateBeer/img'),
        ),
    ]
