# Generated by Django 2.0.13 on 2019-02-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateBeer', '0002_taste_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste',
            name='img_file',
            field=models.FileField(null=True, upload_to='rateBeer/media/rateBeer/img'),
        ),
    ]
