# Generated by Django 2.0.13 on 2019-02-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateBeer', '0003_auto_20190220_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste',
            name='img_file',
            field=models.FileField(null=True, upload_to='media/rateBeer/img'),
        ),
    ]
