# Generated by Django 2.0.13 on 2019-02-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateBeer', '0004_auto_20190220_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taste',
            name='img_file',
        ),
    ]
